-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 22:36:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rehab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rehab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rehab` DEFAULT CHARACTER SET utf8 ;
USE `rehab` ;

-- -----------------------------------------------------
-- Table `rehab`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rehab`.`properties` (
  `property_id` INT NOT NULL AUTO_INCREMENT,
  `p_name` VARCHAR(255) NOT NULL,
  `p_street_address1` VARCHAR(45) NOT NULL,
  `p_street_address2` VARCHAR(45) NULL,
  `p_city` VARCHAR(45) NULL,
  `p_state` VARCHAR(45) NULL,
  `p_zipcode` VARCHAR(45) NULL,
  `p_purchase_date` DATE NULL,
  `p_purchase_price` DOUBLE NULL,
  `p_goal_complete_date` DATE NULL,
  `p_total_budget` DOUBLE NULL,
  PRIMARY KEY (`property_id`),
  UNIQUE INDEX `p_name_UNIQUE` (`p_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rehab`.`contractors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rehab`.`contractors` (
  `contractor_id` INT NOT NULL AUTO_INCREMENT,
  `c_company_name` VARCHAR(45) NULL,
  `c_contact_last_name` VARCHAR(45) NULL,
  `c_contact_first_name` VARCHAR(45) NULL,
  `c_email` VARCHAR(45) NULL,
  `c_phone` VARCHAR(45) NULL,
  `c_street_address1` VARCHAR(45) NULL,
  `c_street_address2` VARCHAR(45) NULL,
  `c_city` VARCHAR(45) NULL,
  `c_state` VARCHAR(45) NULL,
  `c_zipcode` VARCHAR(45) NULL,
  `c_license` VARCHAR(45) NULL,
  `c_insurance` VARCHAR(45) NULL,
  PRIMARY KEY (`contractor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rehab`.`specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rehab`.`specialities` (
  `speciality_id` INT NOT NULL AUTO_INCREMENT,
  `s_type` VARCHAR(45) NULL,
  PRIMARY KEY (`speciality_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rehab`.`contractors_specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rehab`.`contractors_specialities` (
  `contractor_speciality_id` INT NOT NULL AUTO_INCREMENT,
  `cs_contractor` INT NULL,
  `cs_speciality` INT NULL,
  PRIMARY KEY (`contractor_speciality_id`),
  INDEX `contractor_idx` (`cs_contractor` ASC),
  INDEX `speciality_idx` (`cs_speciality` ASC),
  CONSTRAINT `contractor`
    FOREIGN KEY (`cs_contractor`)
    REFERENCES `rehab`.`contractors` (`contractor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `speciality`
    FOREIGN KEY (`cs_speciality`)
    REFERENCES `rehab`.`specialities` (`speciality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rehab`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rehab`.`tasks` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `t_property` INT NOT NULL,
  `t_specialty` INT NULL,
  `t_estimate_selected` INT NULL,
  `t_budget_price` DOUBLE NULL,
  `t_acutal_price` DOUBLE NULL,
  `t_goal_complete_date` DATE NULL,
  `t_acutal_complete_date` DATE NULL,
  `t_detail_description` VARCHAR(255) NULL,
  `t_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`task_id`),
  INDEX `property_idx` (`t_property` ASC),
  INDEX `specialty_idx` (`t_specialty` ASC),
  INDEX `estimate_selected_idx` (`t_estimate_selected` ASC),
  CONSTRAINT `property`
    FOREIGN KEY (`t_property`)
    REFERENCES `rehab`.`properties` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `specialty`
    FOREIGN KEY (`t_specialty`)
    REFERENCES `rehab`.`specialities` (`speciality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estimate_selected`
    FOREIGN KEY (`t_estimate_selected`)
    REFERENCES `rehab`.`estimates` (`estimate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rehab`.`estimates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rehab`.`estimates` (
  `estimate_id` INT NOT NULL AUTO_INCREMENT,
  `e_task` INT NULL,
  `e_contractor` INT NULL,
  `e_quote` DOUBLE NULL,
  `e_deadline` DATE NULL,
  PRIMARY KEY (`estimate_id`),
  INDEX `task_idx` (`e_task` ASC),
  INDEX `contractor_idx` (`e_contractor` ASC),
  CONSTRAINT `task`
    FOREIGN KEY (`e_task`)
    REFERENCES `rehab`.`tasks` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `es_contractor`
    FOREIGN KEY (`e_contractor`)
    REFERENCES `rehab`.`contractors` (`contractor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
